services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_CONNECTION=mongodb://mongo:27017/url-shortener
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: